# This workflow will build Plannr, including the .NET Backend Plannr.Server, and React Frontend plannr.client
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: plannr-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #node-version: [14.x, 16.x, 18.x] Can be used like this to be triggered for each version
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: temp - clean node modules
      run: |
        rm -rf src/plannr.client/node_modules
        rm -f src/plannr.client/package-lock.json

    - name: Build WebUI
      run: |
        cd src/plannr.client
        ls -la
        pwd
        npm install
        npm run build

  build-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Restore dependencies
      run: |
        cd src/Plannr.Server
        ls -la
        pwd
        dotnet restore
    - name: Build WebAPI
      run: |
        cd src/Plannr.Server
        ls -la
        pwd
        dotnet build --no-restore
    - name: Test WebAPI
      run: |
        cd src/Plannr.Server
        ls -la
        pwd
        dotnet test --no-build --verbosity normal
      
